export const dataProperties = [
  {
    id: 1,
    location: "Providencia, Santiago.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 2,
    location: "Viña del mar, Valparaiso.",
    price: 150000000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 3,
    location: "Atacama, Chañaral.",
    price: 350000000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 4,
    location: "Castro, Chiloé.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 5,
    location: "Aysén, Lago Verde.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 6,
    location: "Pucón, Araucanía.",
    price: 300000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 7,
    location: "Los Andes, Valparaíso.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 8,
    location: "Punta Arenas, Magallanes.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 9,
    location: "Parral, Maule.",
    price: 400000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 10,
    location: "San Fabián, Ñuble.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 11,
    location: "Punta Arenas, Magallanes.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 12,
    location: "Providencia, Santiago.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 13,
    location: "Chillán, Ñuble.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 14,
    location: "Peñalolén, Santiago.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 15,
    location: "Concón, Valparaiso.",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
  {
    id: 16,
    location: "Viña del mar, Valparaiso.",
    price: 2000000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. En el corazón de la vibrante ciudad de Santiago de Chile, te presentamos una extraordinaria oportunidad de adquirir una encantadora casa de 120 metros cuadrados que combina comodidad, diseño moderno y una ubicación privilegiada. Situada en un barrio tranquilo y bien conectado, esta propiedad es un verdadero refugio urbano que te invita a disfrutar de la vida en la ciudad sin renunciar a la serenidad. ",
  },
];
